---
title: "PAC, CFA, and Moderation"
author: "Hayden Spence"
output:
  word_document: default
  html_document: default
---

```{r}
wants <- c("mediation", "multilevel", "QuantPsyc")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```

```{r}
path = file.path("C:", "Users/PC/Dropbox/R_Notebooks/Final", "cleanfile4.csv")
dt = read_csv(path)
```

```{r}
# Removing Gender from list of variables 
listVar <- c("age", "gender", "race", "ethnic", "city", "living", "icd10", "insurance", "dx", "phone_disposition", "team_sent", "time", "resp_time", "respite_location", "bed_days", "mobile_disposition")
#Define categorical variables
catVar <- c("gender", "race", "ethnic", "living", "city", "icd10", "insurance", "dx", "phone_disposition", "team_sent", "mobile_disposition", "respite_location" )
```
```{r}
table1 <- CreateTableOne(vars = listVar, data = dt, factorVars = catVar)
table1
```

```{r}
X <- (data$bed_days)
M <- (data$gender)
Y <- (data$time)
```

```{r}
Xc <- c(scale(dfRegr$X, center=TRUE, scale=FALSE))
Mc <- c(scale(dfRegr$M, center=TRUE, scale=FALSE))
fitMod <- lm(Y ~ Xc + Mc + Xc:Mc, data=dfRegr)
summary(fitMod)
```

```{r}
boxplot(data$bed_days, main="Bed Days")
boxplot(data$time, main="Time")
```

```{r}
wants <- c("energy", "ICS", "mvtnorm", "nortest", "QuantPsyc", "tseries")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
```




